version: "3"
services:

  jenkins:
    build: ./
    privileged: false
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    container_name: jenkins
    volumes: 
      - /var/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker 

